#!/usr/bin/env python3
"""Crawl IDX universe sector/industry metadata.

Sources:
1. Local universe file (/opt/data/idx_full_universe_current.txt)
2. Yahoo Finance quoteSummary assetProfile for SYMBOL.JK
3. Existing zeta_industry.py fallback labels

Outputs:
- data/idx_sectors.csv
- app/data/idx_sectors.py
"""
from __future__ import annotations

import csv
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

try:
    import yfinance as yf
except Exception:  # pragma: no cover
    yf = None

ROOT = Path(__file__).resolve().parents[1]
UNIVERSE = Path("/opt/data/idx_full_universe_current.txt")
OUT_CSV = ROOT / "data" / "idx_sectors.csv"
OUT_PY = ROOT / "app" / "data" / "idx_sectors.py"
CACHE = ROOT / "data" / "idx_sectors_cache.json"

YAHOO_CHART = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}.JK?range=1d&interval=1d"
YAHOO_PROFILE = "https://query1.finance.yahoo.com/v10/finance/quoteSummary/{symbol}.JK?modules=assetProfile,price"

USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36"

FALLBACK_MAP = {
    "BBCA":"Financial Services", "BBRI":"Financial Services", "BMRI":"Financial Services", "BBNI":"Financial Services", "BBTN":"Financial Services", "BRIS":"Financial Services",
    "ADRO":"Energy", "ITMG":"Energy", "PTBA":"Energy", "HRUM":"Energy", "BREN":"Energy", "BRPT":"Basic Materials",
    "PTRO":"Energy", "RAJA":"Energy", "MEDC":"Energy", "ELSA":"Energy", "PGAS":"Utilities",
    "TLKM":"Communication Services", "EXCL":"Communication Services", "ISAT":"Communication Services", "FREN":"Communication Services",
    "ASII":"Consumer Cyclical", "AUTO":"Consumer Cyclical",
    "GOTO":"Technology", "BUKA":"Technology", "WIFI":"Communication Services",
    "ICBP":"Consumer Defensive", "INDF":"Consumer Defensive", "UNVR":"Consumer Defensive", "MYOR":"Consumer Defensive", "SIDO":"Healthcare",
    "SILO":"Healthcare", "MIKA":"Healthcare", "HEAL":"Healthcare", "SAME":"Healthcare",
    "ANTM":"Basic Materials", "MDKA":"Basic Materials", "AMMN":"Basic Materials", "INCO":"Basic Materials", "TINS":"Basic Materials",
}


def load_symbols() -> list[str]:
    return [x.strip().upper().replace(".JK", "") for x in UNIVERSE.read_text().splitlines() if x.strip()]


def http_json(url: str, timeout: int = 12) -> dict | None:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            if r.status != 200:
                return None
            return json.loads(r.read().decode("utf-8", errors="ignore"))
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, json.JSONDecodeError):
        return None


def fetch_yahoo_profile(symbol: str) -> dict:
    if yf is not None:
        try:
            info = yf.Ticker(f"{symbol}.JK").info
            return {
                "sector": info.get("sector") or "",
                "industry": info.get("industry") or "",
                "long_name": info.get("longName") or "",
                "exchange": info.get("exchange") or "",
            }
        except Exception:
            pass
    return {}


def fallback(symbol: str) -> dict:
    sector = FALLBACK_MAP.get(symbol, "Unknown")
    return {"sector": sector, "industry": "", "long_name": "", "exchange": "fallback"}


def main() -> int:
    symbols = load_symbols()
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    OUT_PY.parent.mkdir(parents=True, exist_ok=True)
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    rows = []
    for i, symbol in enumerate(symbols, 1):
        rec = cache.get(symbol)
        if not rec or not rec.get("sector"):
            rec = fetch_yahoo_profile(symbol)
            if not rec.get("sector"):
                rec = fallback(symbol)
            cache[symbol] = rec
            CACHE.write_text(json.dumps(cache, indent=2, sort_keys=True))
            time.sleep(0.18)
        rows.append({"symbol": symbol, **rec})
        if i % 25 == 0:
            known = sum(1 for r in rows if r.get("sector") and r.get("sector") != "Unknown")
            print(f"{i}/{len(symbols)} known={known}", flush=True)

    with OUT_CSV.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["symbol", "sector", "industry", "long_name", "exchange"])
        w.writeheader()
        w.writerows(rows)

    mapping = {r["symbol"]: {"sector": r.get("sector") or "Unknown", "industry": r.get("industry") or "", "name": r.get("long_name") or ""} for r in rows}
    py = "# Auto-generated by scripts/crawl_idx_sectors.py\n" \
         "# Source universe: /opt/data/idx_full_universe_current.txt + Yahoo Finance assetProfile\n\n" \
         f"IDX_SECTORS = {json.dumps(mapping, indent=4, sort_keys=True)}\n\n" \
         "def get_sector(symbol: str) -> str:\n" \
         "    return IDX_SECTORS.get(symbol.upper().replace('.JK', ''), {}).get('sector', 'Unknown')\n\n" \
         "def get_industry(symbol: str) -> str:\n" \
         "    return IDX_SECTORS.get(symbol.upper().replace('.JK', ''), {}).get('industry', '')\n\n" \
         "def get_profile(symbol: str) -> dict:\n" \
         "    return IDX_SECTORS.get(symbol.upper().replace('.JK', ''), {'sector': 'Unknown', 'industry': '', 'name': ''})\n"
    OUT_PY.write_text(py)

    known = sum(1 for r in rows if r.get("sector") and r.get("sector") != "Unknown")
    print(f"DONE symbols={len(rows)} known_sectors={known} unknown={len(rows)-known}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
